version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    command: 'bundle exec foreman start -f Procfile'

    depends_on:
      - db
      - redis

    dns: 8.8.8.8

    environment:
      - CI
      - PORT=3000
      - REDIS_URL=redis://redis:6379

    ports:
      - '3000:3000'

    volumes:
      - .:/app
      - ./config/database.docker.yml:/app/config/database.yml

  db:
    image: postgres:9.6.3
    environment:
      POSTGRES_USER: multi-aggregator
      POSTGRES_PASSWORD: multi-aggregator

  redis:
    image: redis:3.2.5
